- name: play level variables
  hosts: local
  connection: local
  vars:
    coures: "devops with aws"
    duration: "140hrs"
    trainer : "siva"
  tasks:
  - name: print variable
    ansible.builtin.debug:
      msg: "coures is: {{ coures }, trainer is: {trainer }}"