- name: play level variables
  hosts: local
  connection: local
  vars_files:
  - coures.yaml
  tasks:
  - name: print variable
    ansible.builtin.debug:
      msg: "coures is: {{ coures }}, trainer is: {{ trainer }}"