- name: play level variables
  hosts: localhost
  connection: local
  vars:
    course: "devops with aws"
    duration: "140hrs"
    trainer: "siva"

  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: "course is: {{ course }}, trainer is: {{ trainer }}"