- name: vars performance
  hosts: localhost
  connection: local

  vars:
    name: "ansible from play"

  vars_prompt:
    - name: name
      prompt: "please enter the user name"
      private: false

  tasks:
    - name: print the name
      vars:
        name: "ansible from task"
      ansible.builtin.debug:
        msg: "Hi {{ name }}"