- name: demo on data types
  hosts: localhost
  connection: local

  vars:
    Program: "aws devops with devsecops" # string
    Duration: "140Hrs"  # int/number
    IS_Live: true  # bool
    Details:    # map/dictinory
      trainer: "jai yadav"
      Months: 6
    Topics:   # list -/[]
      - linux
      - devops
      - aws

  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: |
          Program: {{ Program }}
          Duration: {{ Duration }}
          IS_Live?: {{ IS_Live }}
          Details: {{ Details }}
          Topics: {{ Topics }}