- name: demo on data types
  hosts: localhost
  connection: local

  vars:
    Program: "aws devops with devsecops"
    Duration: "140Hrs"
    IS_Live: true
    Details:
      trainer: "jai yadav"
      Months: 6
    Topics:
      - linux
      - devops
      - aws

  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: |
          Program: {{ Program }}
          Duration: {{ Duration }}
          IS_Live?: {{ IS_Live }}
          Details: {{ Details }}
          Topics: {{ Topics }}