- name: demo on conditions                       
  hosts: local
  connection: local
 
  vars:
    IS_Live: true 

  tasks:
  - name: check live or not 
    ansible.builtin.debug:
      msg: "Yes,it is live"
    when: IS_Live
  
  - name: check if not live 
    ansible.builtin.debug:
      msg: "No,it is Not live"
    when: not IS_Live