- name: demo on error handling
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: check the user exists or not
      ansible.builtin.command: id roboshop
      register: user_output
      ignore_errors: yes   # ✅ important

    - name: print the output 
      ansible.builtin.debug:
        msg: "{{ user_output }}"

    - name: create the user
      ansible.builtin.command: useradd roboshop
      when: user_output.rc != 0