- name: demo on error handling
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: check the user is exit or not
    ansible.builtin.command: id roboshop
    register: user_output
  
  - name: print the output 
    ansible.builtin.debug:
      msg: "{{ user_output }}"

  - name: creat the user jai
    ansible.builtin.user:
      name: jai 


  